version : "3.6"

services :

    nodets-back :
        restart : unless-stopped
        container_name : nodets-back
        build : .
        ports :
            - "5001:5001"
        depends_on :
            - "mongo"
        links :
            - "mongo"
        env_file :
            - .env

    mongo :
        container_name : mongodb
        image : "mongo"
        restart : unless-stopped
        volumes :
            - mongo-data:/data/db
        env_file :
          - .mongo.env
        expose :
            - "27017"

volumes :
    mongo-data:
